# res://Scripts/main_level_manager.gd
extends Node
class_name MainLevelManager

signal main_level_up(new_level: int)
signal main_exp_gained(amount: int, new_total: int)

# ── Tuning constants ─────────────────────────────────────────
# World Level now extends to match MnemosyneProgressTracker.progression_map's
# top key (225), since muse card upgrades are gated by world level thresholds.
# Hand-typing 225 threshold/multiplier entries isn't maintainable, so both are
# generated by formula in _generate_curves() and cached at startup.
const MAX_LEVEL: int = 225

# XP_THRESHOLDS[i] = total main_exp required to REACH level (i+1).
# Index 0 = level 1 baseline (0 exp, starting level).
# Curve: quadratic-ish ramp, tunable via the constants below.
const THRESHOLD_BASE: float = 50.0
const THRESHOLD_GROWTH: float = 1.035  # per-level compounding growth

# MULTIPLIERS[i] = XP multiplier at level (i+1). Grows slower than thresholds
# and is capped so late-game multipliers don't spiral.
const MULTIPLIER_BASE: float = 1.0
const MULTIPLIER_GROWTH: float = 1.01
const MULTIPLIER_CAP: float = 5.0

var XP_THRESHOLDS: Array[int] = []
var MULTIPLIERS: Array[float] = []

# Base exp awards for events - adjust these values as needed
const EXP_WIN: int = 10
const EXP_LOSS: int = 5
const EXP_CARD_LEVEL_UP: int = 8  # Per level gained, not per card

# ── State ─────────────────────────────────────────────────────
var main_level: int = 1
var main_exp: int = 0

var save_path: String = "user://main_level.save"

# ── Lifecycle ─────────────────────────────────────────────────
func _ready():
	_generate_curves()
	load_data()

# ── Core API ──────────────────────────────────────────────────

# Add exp to the main level. Call this from any event site.
func add_main_exp(amount: int):
	if main_level >= MAX_LEVEL:
		return

	main_exp += amount
	emit_signal("main_exp_gained", amount, main_exp)
	print("MainLevel: +", amount, " exp (total: ", main_exp, ", level: ", main_level, ")")

	_check_level_up()
	save_data()

# Apply the current level's multiplier to a base XP value and return floored int.
# Use this at every site where card or bestiary XP is awarded.
func apply_xp(base_amount: int) -> int:
	return floori(base_amount * get_multiplier())

# Returns the multiplier for the current level
func get_multiplier() -> float:
	var index = clamp(main_level - 1, 0, MULTIPLIERS.size() - 1)
	return MULTIPLIERS[index]

# Returns exp needed to reach the next level (0 if at max)
func get_exp_to_next_level() -> int:
	if main_level >= MAX_LEVEL:
		return 0
	return XP_THRESHOLDS[main_level] - main_exp

# Returns progress through current level as 0.0–1.0
func get_level_progress_pct() -> float:
	if main_level >= MAX_LEVEL:
		return 1.0
	var prev_threshold = XP_THRESHOLDS[main_level - 1]
	var next_threshold = XP_THRESHOLDS[main_level]
	var span = next_threshold - prev_threshold
	if span <= 0:
		return 1.0
	return float(main_exp - prev_threshold) / float(span)

# ── Internal ──────────────────────────────────────────────────

func _check_level_up():
	while main_level < MAX_LEVEL and main_exp >= XP_THRESHOLDS[main_level]:
		main_level += 1
		emit_signal("main_level_up", main_level)
		print("MainLevel: LEVEL UP → Level ", main_level, " (multiplier now ", get_multiplier(), "x)")

# ── Save / Load ───────────────────────────────────────────────

func save_data():
	var save_file = FileAccess.open(save_path, FileAccess.WRITE)
	if save_file:
		save_file.store_var({"main_level": main_level, "main_exp": main_exp})
		save_file.close()
	else:
		print("MainLevelManager: Failed to save!")

func load_data():
	if FileAccess.file_exists(save_path):
		var save_file = FileAccess.open(save_path, FileAccess.READ)
		if save_file:
			var data = save_file.get_var()
			save_file.close()
			main_level = data.get("main_level", 1)
			main_exp = data.get("main_exp", 0)
			print("MainLevelManager: Loaded - Level ", main_level, ", Exp ", main_exp)
	else:
		print("MainLevelManager: No save found, starting fresh")

# Called by new game confirmation - wipes all progress
func reset():
	main_level = 1
	main_exp = 0
	save_data()
	print("MainLevelManager: Reset to Level 1")

func _generate_curves():
	XP_THRESHOLDS.resize(MAX_LEVEL)
	MULTIPLIERS.resize(MAX_LEVEL)
	XP_THRESHOLDS[0] = 0
	MULTIPLIERS[0] = MULTIPLIER_BASE
	for i in range(1, MAX_LEVEL):
		var prev_threshold = XP_THRESHOLDS[i - 1]
		var increment = THRESHOLD_BASE * pow(THRESHOLD_GROWTH, i)
		XP_THRESHOLDS[i] = prev_threshold + roundi(increment)
		MULTIPLIERS[i] = min(MULTIPLIER_BASE * pow(MULTIPLIER_GROWTH, i), MULTIPLIER_CAP)

# Returns true if the given level is within range (used by callers needing
# a simple bounds check before reading threshold/multiplier arrays directly).
func is_valid_level(level: int) -> bool:
	return level >= 1 and level <= MAX_LEVEL
